
import { Internship, User, Trainer } from './types';

export const INTERNSHIPS: Internship[] = [
  {
    id: 1,
    title: 'Frontend Web Developer',
    domain: 'Web Development',
    description: 'Work with modern frontend frameworks like React to build stunning user interfaces. Collaborate with UI/UX designers and backend developers to create a seamless user experience.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Tailwind CSS', 'Git'],
  },
  {
    id: 2,
    title: 'Backend Developer (Django)',
    domain: 'Backend Development',
    description: 'Design and implement server-side logic, manage databases, and create robust APIs using Python and Django. A great opportunity to learn about scalability and security.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Python', 'Django', 'REST APIs', 'PostgreSQL', 'Docker'],
  },
  {
    id: 3,
    title: 'Mobile App Developer (React Native)',
    domain: 'App Development',
    description: 'Develop cross-platform mobile applications for iOS and Android using React Native. You will be responsible for the full development lifecycle from concept to deployment.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['React Native', 'JavaScript', 'Redux', 'APIs', 'Firebase'],
  },
  {
    id: 4,
    title: 'Data Science Intern',
    domain: 'Data Science',
    description: 'Analyze large datasets to extract meaningful insights. Build predictive models and use machine learning techniques to solve real-world problems. Work with tools like Pandas, NumPy, and Scikit-learn.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'SQL', 'Jupyter'],
  },
  {
    id: 5,
    title: 'UI/UX Design Intern',
    domain: 'Design',
    description: 'Create intuitive and visually appealing user interfaces. Conduct user research, create wireframes and prototypes, and work closely with developers to implement your designs.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Wireframing'],
  },
    {
    id: 6,
    title: 'Cloud Engineering Intern (AWS)',
    domain: 'Cloud Computing',
    description: 'Gain hands-on experience with Amazon Web Services (AWS). Work on deploying, managing, and scaling applications in the cloud. Learn about services like EC2, S3, Lambda, and RDS.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['AWS', 'Linux', 'Networking', 'Terraform', 'CI/CD'],
  },
  {
    id: 7,
    title: 'DevOps Internship',
    domain: 'DevOps',
    description: 'Master the art of continuous integration and deployment. Learn to automate infrastructure, manage containerized applications, and implement CI/CD pipelines. Work with industry-standard tools and practices.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Jenkins', 'Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux'],
  },
  {
    id: 8,
    title: 'SecOps Internship',
    domain: 'Security & DevOps',
    description: 'Learn security-focused DevOps practices. Implement secure infrastructure, conduct security audits, and manage vulnerability assessments. Build secure pipelines and hardened deployments.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Security Tools', 'SIEM', 'Compliance', 'Infrastructure Security', 'Penetration Testing', 'Docker'],
  },
  {
    id: 9,
    title: 'Docker and Kubernetes Internship',
    domain: 'Containerization',
    description: 'Deep dive into containerization with Docker and container orchestration with Kubernetes. Build, deploy, and manage containerized applications at scale.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Docker', 'Kubernetes', 'Container Orchestration', 'Docker Compose', 'kubectl', 'YAML'],
  },
  {
    id: 10,
    title: 'Hands on Git & Github',
    domain: 'Version Control',
    description: 'Master version control with Git and GitHub. Learn branching strategies, collaboration workflows, and best practices for team development. Understand pull requests, merges, and conflict resolution.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Git', 'GitHub', 'Branching', 'Merging', 'Collaboration', 'GitHub Actions'],
  },
  {
    id: 11,
    title: 'Hands on Linux',
    domain: 'Linux & System Administration',
    description: 'Comprehensive hands-on training in Linux operating system. Learn system administration, file management, networking, and command-line mastery. Perfect foundation for DevOps and system roles.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Linux Commands', 'File System', 'User Management', 'Networking', 'System Administration', 'Bash'],
  },
  {
    id: 12,
    title: 'Hands on Shell Scripting',
    domain: 'Scripting',
    description: 'Learn to automate tasks with shell scripting. Master bash scripting, text processing, and automation techniques. Write efficient scripts for system administration and DevOps tasks.',
    duration: '3 Months',
    stipend: 'Performance-based',
    skills: ['Bash', 'Shell Scripting', 'Automation', 'Text Processing', 'Regular Expressions', 'AWK/SED'],
  }
];

export const MOCK_USERS: User[] = [
    { id: 1, email: 'admin@example.com', password: 'adminpassword', role: 'admin', appliedInternships: [] },
    { id: 2, email: 'user@example.com', password: 'userpassword', role: 'user', appliedInternships: [1, 4] },
];

export const TRAINERS: Trainer[] = [
  {
    id: 1,
    name: 'Sudhanshu Verma',
    domain: 'Full Stack & Web Development',
    expertise: ['React', 'JavaScript', 'HTML/CSS', 'Tailwind CSS', 'Python', 'Django', 'REST APIs', 'PostgreSQL', 'Git', 'GitHub'],
    experience: '7 years',
    bio: 'Senior Full Stack Developer with expertise across all web technologies. Sarah guides interns through frontend development, backend systems, and version control best practices. She excels at teaching modern development workflows and industry standards.',
    availability: 'Mon, Wed, Fri (2-4 PM)',
  },
  {
    id: 2,
    name: 'Brijesh Sharma',
    domain: 'DevOps, Cloud & Infrastructure',
    expertise: ['AWS', 'Docker', 'Kubernetes', 'Linux', 'Jenkins', 'CI/CD', 'Terraform', 'Networking', 'System Administration', 'Shell Scripting'],
    experience: '6 years',
    bio: 'Cloud & DevOps expert with comprehensive knowledge of infrastructure, containerization, and deployment. Rajesh mentors interns on cloud engineering, DevOps practices, Linux systems, Docker, Kubernetes, and shell scripting. Perfect for all infrastructure-related internships.',
    availability: 'Tue, Thu (3-5 PM)',
  },
  {
    id: 3,
    name: 'Akash Kumar',
    domain: 'Mobile & Cross-Platform Development',
    expertise: ['React Native', 'JavaScript', 'Redux', 'Firebase', 'APIs', 'Mobile Development', 'UX Design', 'Figma', 'Prototyping', 'Wireframing'],
    experience: '4 years',
    bio: 'Mobile development specialist with expertise in cross-platform applications and design. Emily guides interns through mobile app development with React Native, UI/UX design principles, user research, and prototyping. She combines technical and design knowledge seamlessly.',
    availability: 'Mon, Wed, Fri (1-3 PM)',
  },
  {
    id: 4,
    name: 'Savita Kumari',
    domain: 'Data Science & Advanced Analytics',
    expertise: ['Python', 'Machine Learning', 'Data Analysis', 'SQL', 'TensorFlow', 'Pandas', 'NumPy', 'Scikit-learn', 'Jupyter', 'Data Visualization'],
    experience: '3 years',
    bio: 'Data Science expert with deep expertise in machine learning and data analytics. David mentors interns on data analysis, predictive modeling, deep learning, and real-world data science applications. He helps students understand how to extract meaningful insights from data.',
    availability: 'Tue, Thu, Sat (4-6 PM)',
  },
];
